### PR TITLE
[GLUTEN-12951][VL] Flatten backends-velox POM to preserve Arrow profile versions

### LINKED ISSUE #12951: [VL] Installed backends-velox POM resolves wrong Arrow version for Spark 4.x module builds
### Backend

VL (Velox)

### Bug description

**Expected behavior:** Installing `backends-velox` with a Spark 4.x profile should publish dependency metadata containing that profile's resolved Arrow version and scopes. A later module-only build should therefore resolve one consistent Arrow version.

**Actual behavior:** The installed `backends-velox` POM retains `${arrow.version}`. When a consumer runs outside the original Maven reactor, Maven resolves that property from the parent default (`15.0.0`) even though Spark 4.0 and 4.1 select Arrow `18.1.0` and `18.3.0`, respectively. This can mix Arrow 15 and 18 artifacts on the test classpath.

A Spark 4.1 module-only test then fails with:

```text
java.lang.NoClassDefFoundError: org/apache/arrow/vector/types/pojo/ArrowType$Utf8View
```

Reproduction:

1. Install Gluten with the Velox, Spark 4.1, Java 17, and Scala 2.13 profiles.
2. In a subsequent Maven invocation, run only the Spark 4.1 unit-test module without `-am`, so Maven consumes the installed `backends-velox` POM.
3. Inspect the dependency tree or run tests.
4. Observe `arrow-c-data:18.3.0` alongside `arrow-vector:15.0.0`, followed by the missing `ArrowType$Utf8View` class.

Running with `-am` masks the problem by keeping `backends-velox` in the active Spark-profile reactor. The installed and published POM should instead contain flattened, profile-resolved metadata.

This issue was co-authored with GitHub Copilot CLI 1.0.80.

### Gluten version

main branch

### Spark version

Spark-4.0.x and Spark-4.1.x

### Spark configurations

Maven profiles:

```text
-Pbackends-velox -Pspark-4.1 -Pscala-2.13 -Pjava-17
```

The equivalent Spark 4.0 profile is also affected. Spark 3.3–3.5 intentionally use Arrow 15.0.0 and should remain unchanged.

### System information

Reproduced in the local Gluten Linux development container using JDK 17 and Maven through `./build/mvn`.

### Relevant logs

```text
arrow-c-data:18.3.0
arrow-vector:15.0.0
java.lang.NoClassDefFoundError: org/apache/arrow/vector/types/pojo/ArrowType$Utf8View
```

A full reactor build with `-am` resolves Arrow 18.3.0 consistently, confirming that the failure depends on consuming the installed POM.

### PR DESCRIPTION
**Pull request by jianyexi**
Fixes #12951

## What changes are proposed in this pull request?

Enable the parent-managed `flatten-maven-plugin` for `backends-velox` so its installed and published POM records the Arrow version and scopes selected by the active Spark profile.

Without flattening, the installed backend POM retains `${arrow.version}`. A standalone Spark 4.0 or 4.1 module build can then resolve that property from the parent default (Arrow 15.0.0) while Spark supplies other Arrow components at 18.x. This produces a mixed classpath and caused `NoClassDefFoundError: ArrowType$Utf8View` in Spark 4.1 tests. Full reactor builds mask the defect because the active Spark profile remains available.

The change affects published Maven metadata only; it does not alter Gluten runtime behavior. Spark 3.x continues to resolve Arrow 15.0.0.

## How was this patch tested?

Validated flattened dependency metadata across all supported Spark profiles:

- Spark 3.3, 3.4, and 3.5: Arrow 15.0.0 with existing runtime/compile scopes.
- Spark 4.0: Arrow 18.1.0 with provided scope.
- Spark 4.1: Arrow 18.3.0 with provided scope.
- No unresolved `${arrow...}` expressions remained.
- Maven's lifecycle-generated and installed Spark 4.1 POMs were byte-identical.
- `backends-velox/pom.xml` parses as valid XML.
- `git diff --check` passed.

## Was this patch authored or co-authored using generative AI tooling?

Co-authored-by: GitHub Copilot CLI 1.0.80

### CODE REVIEW

**Comment by jianyexi** [comment]
Closing as superseded by #12932, which independently identified the same root cause, added the identical parent-managed flatten-maven-plugin declaration, validated the Spark 4.1 module-only test, and has already merged into main. After main was merged into this branch, both declarations appeared in backends-velox/pom.xml, producing the duplicate-plugin review warning.
