### PR TITLE
[CORE] Unbundle Arrow memory + vector from gluten-velox-bundle (Draft)

### PR DESCRIPTION
**Pull request by sezruby**
**Draft.** Stacked on #12244. The diff below is what the unbundle looks like in pom-form; cross-distro testing (vanilla 3.5, DBR 16.4, Cloudera, 4.0/4.1) is still TODO and gates merge.

## What changes were proposed in this pull request?

Stop bundling \`arrow-memory-*\` and \`arrow-vector\` in \`gluten-velox-bundle\`. Mark them as \`scope=provided\` in \`gluten-arrow/pom.xml\` and rely on Spark's own Arrow distribution at runtime (\`\$SPARK_HOME/jars/\` for Spark 3.x; declared in Spark 4.x's pom).

\`arrow-c-data\` and \`arrow-dataset\` stay bundled — Spark does not ship those.

## Why

Follow-up from #12226 discussion. The bundled-and-shaded-Arrow approach is the source of #12225 (and similar #7423): when gluten's bundle wins classloader resolution, its class signatures collide with the user's vanilla Arrow. #12226 fixed the immediate \`NoSuchMethodError\` by un-shading; but as @zhztheplayer noted, "Memory and vector APIs should be stable across minor versions" is a real risk worth eliminating: the cleanest fix is to not ship them at all.

Effects:
* gluten-velox-bundle no longer contains any \`org.apache.arrow.memory.*\` or \`org.apache.arrow.vector.*\` classes. Class-shadowing from #12225 disappears by construction.
* The \`org.apache.arrow\` shade-relocation block in \`package/pom.xml\` is removed (nothing to relocate, since memory/vector aren't bundled and c-data/dataset were already excluded).
* \`arrow-c-data\` / \`arrow-dataset\` remain bundled. With no relocation, their public API signatures bind to vanilla \`BufferAllocator\` / \`VectorSchemaRoot\` — exactly what every other Arrow C-Data caller on the classpath expects.
* \`backends-velox/pom.xml\` re-declares \`arrow-memory-core\` and \`arrow-vector\` at \`provided\` scope so its compile classpath still resolves them after the gluten-arrow scope flip. \`gluten-ut/*\` and \`backends-clickhouse\` already declare them locally.

## Open questions / why this is a Draft

1. **\`arrow.version\` pin per Spark distro.** \`<arrow.version>15.0.0</arrow.version>\` matches vanilla Spark 3.5.x. DBR 16.4 ships Spark 3.5 with Arrow 12.0.1 — gluten compiled against 15 might \`NoSuchMethodError\` on DBR. Need to either (a) downgrade to LCD 12.0.1 for the Spark-3.5 profile, or (b) add a DBR-specific profile, or (c) declare gluten as DBR-incompatible. Cloudera flavors need similar verification.
2. **Cross-distro test matrix.** Want to actually run the gluten test suite against vanilla 3.5, DBR 16.4, Cloudera CDS, and 4.0/4.1 before merging. CI here only covers vanilla.
3. **Velox C++ side still uses bundled Arrow.** The cpp side links its own Arrow (the C++ patches in \`ep/build-velox/src/modify_arrow.patch\`); this PR only changes JVM-side bundling. The JVM ↔ C++ exchange happens via Arrow C-Data's stable ABI, so the JVM-side Arrow version doesn't need to match the C++-side one. Worth noting in case anyone assumes they should track.
4. \`dev/check-arrow-c-shading.sh\` from #12226 still passes — bundle still has \`org/apache/arrow/c/*\` and their signatures now reference unshaded \`memory.*\` / \`vector.*\` types (which resolve from Spark's bundled Arrow at runtime).

## How was this patch tested?

Local build only. CI green needed before un-drafting.

## Closes / refs

* Follow-up from #12226 discussion (zhztheplayer + FelixYBW asked for this direction).
* Subsumes the immediate need for #12226's \`dev/check-arrow-c-shading.sh\` if the bundle fully stops containing memory/vector classes — but the script remains useful as a regression guard for the c-data classes still in the bundle.

Stacked on:
* #12244 — drop the \`15.0.0-gluten\` Arrow version rename

### CODE REVIEW

**Comment by sezruby** [comment]
Closing this — the unbundling direction turns out to be incompatible with gluten's current Spark 3.3 / 3.4 support, and I don't think the workaround is worth the risk.

cc @zhztheplayer @FelixYBW

**What CI showed.** Spark 3.5 / 4.0 / 4.1 lanes were on track, but `spark-test-spark33` and `spark-test-spark34` (and several `tpc-test-*` lanes built against them) failed early. Root cause traced to the bundled-Arrow being load-bearing for older Spark:

- Spark 3.3.1 ships Arrow 7.0.0
- Spark 3.4.4 ships Arrow 11.0.0
- Spark 3.5.5 ships Arrow 15.0.0
- Spark 4.0.x / 4.1.x ship Arrow 18.x

Gluten's parent `pom.xml` pins `<arrow.version>15.0.0</arrow.version>` and uses it at compile scope. Today that works because gluten bundles its own Arrow 15 into the velox bundle, which wins classloader resolution at runtime over Spark's older Arrow.

Once `arrow-memory-*` / `arrow-vector` flip to `scope=provided` (this PR), the bundle stops shipping Arrow. The compile classpath still has 15, but at runtime on Spark 3.3 / 3.4 only the older Arrow (7 / 11) is on the classpath — `NoSuchMethodError` / `NoClassDefFoundError` follow.

**Workarounds considered.**

1. Per-Spark-profile `<arrow.version>` overrides (3.3→7.0, 3.4→11.0, 3.5→15.0, 4.x→18.1). Compiles, but ships gluten built against Arrow 7 on the 3.3 profile — exactly the "API stability across versions" concern you raised on [#12226](https://github.com/apache/gluten/pull/12226) (`> Memory and vector APIs should be stable across minor versions / This sounds a real risk`), now applied across an *eight-version* gap rather than a one-or-two-version gap. Surface area too large to be confident without per-version testing.
2. Conditional `<scope>` (provided on 3.5+, compile on 3.3/3.4). Works mechanically but is ugly and leaves the bug ([#12225](https://github.com/apache/gluten/issues/12225)) latent on Spark 3.3 / 3.4.
3. Drop Spark 3.3 / 3.4 support. Out of scope for this fix.

None feels worth it as a one-shot, especially since [#12226](https://github.com/apache/gluten/pull/12226) already neutralized the immediate `NoSuchMethodError` from [#12225](https://github.com/apache/gluten/issues/12225) by un-shading the boundary types.

**What I'm keeping.** [#12244](https://github.com/apache/gluten/pull/12244) — drop the `15.0.0-gluten` artifact rename, drop the dead `modify_arrow_dataset_scan_option.patch` from the Arrow JVM build, depend on vanilla Apache Arrow from Maven Central. CI green there. That gives non-ppc64le contributors a faster build-from-source path without changing the runtime/bundling story.

**For follow-up.** If gluten ever drops Spark 3.3 / 3.4, this unbundling work is small — the diff is ~3 poms. Happy to revisit then.
