### ISSUE TITLE
[VL] Installed backends-velox POM resolves wrong Arrow version for Spark 4.x module builds

### ISSUE THREAD

**Issue by jianyexi** [apache/gluten#12951]
### Backend

VL (Velox)

### Bug description

**Expected behavior:** Installing `backends-velox` with a Spark 4.x profile should publish dependency metadata containing that profile's resolved Arrow version and scopes. A later module-only build should therefore resolve one consistent Arrow version.

**Actual behavior:** The installed `backends-velox` POM retains `${arrow.version}`. When a consumer runs outside the original Maven reactor, Maven resolves that property from the parent default (`15.0.0`) even though Spark 4.0 and 4.1 select Arrow `18.1.0` and `18.3.0`, respectively. This can mix Arrow 15 and 18 artifacts on the test classpath.

A Spark 4.1 module-only test then fails with:

```text
java.lang.NoClassDefFoundError: org/apache/arrow/vector/types/pojo/ArrowType$Utf8View
```

Reproduction:

1. Install Gluten with the Velox, Spark 4.1, Java 17, and Scala 2.13 profiles.
2. In a subsequent Maven invocation, run only the Spark 4.1 unit-test module without `-am`, so Maven consumes the installed `backends-velox` POM.
3. Inspect the dependency tree or run tests.
4. Observe `arrow-c-data:18.3.0` alongside `arrow-vector:15.0.0`, followed by the missing `ArrowType$Utf8View` class.

Running with `-am` masks the problem by keeping `backends-velox` in the active Spark-profile reactor. The installed and published POM should instead contain flattened, profile-resolved metadata.

This issue was co-authored with GitHub Copilot CLI 1.0.80.

### Gluten version

main branch

### Spark version

Spark-4.0.x and Spark-4.1.x

### Spark configurations

Maven profiles:

```text
-Pbackends-velox -Pspark-4.1 -Pscala-2.13 -Pjava-17
```

The equivalent Spark 4.0 profile is also affected. Spark 3.3–3.5 intentionally use Arrow 15.0.0 and should remain unchanged.

### System information

Reproduced in the local Gluten Linux development container using JDK 17 and Maven through `./build/mvn`.

### Relevant logs

```text
arrow-c-data:18.3.0
arrow-vector:15.0.0
java.lang.NoClassDefFoundError: org/apache/arrow/vector/types/pojo/ArrowType$Utf8View
```

A full reactor build with `-am` resolves Arrow 18.3.0 consistently, confirming that the failure depends on consuming the installed POM.

**Comment by jianyexi** [comment]
Resolved by #12932, merged in commit `3e1962eb417f08b70b9b866af448dc1905cb32f5`.

Root cause: `backends-velox` did not activate the parent-managed `flatten-maven-plugin`, so its installed POM retained the profile-dependent `${arrow.version}` expression. A later Spark 4.x module-only Maven invocation resolved that expression through the parent default (Arrow 15) while other dependencies used Arrow 18, causing the mixed classpath and missing `ArrowType$Utf8View`. The merged fix publishes profile-resolved dependency metadata.
